In [5]:
import numpy as np
from numpy.linalg import inv, det

1. BuatlahTensor di bawah ini dengan Python: [[[[23,50],[7,12]],[[57.67],[99,43]]],[[[75,21],[57,12]],[[87,26],[18,84]]]


In [12]:
t = np.array([[[[23,50],[7,12]],[[57,67],[99,43]]],[[[75,21],[57,12]],[[87,26],[18,84]]]])
print(t)

[[[[23 50]
   [ 7 12]]

  [[57 67]
   [99 43]]]


 [[[75 21]
   [57 12]]

  [[87 26]
   [18 84]]]]


2. Lakukan perkalian terhadap matrix berikut:

$$ 
A = \begin{bmatrix} 
23 & 50 & 19 \\
7 & 12 & 109 \\
57 & 67 & 98 
\end{bmatrix} 
\begin{bmatrix} 
17 \\ 
22 \\
19 
\end{bmatrix} 
$$

In [3]:
m = np.array([[23, 50, 19],[ 7, 12, 109],[ 57, 67, 98]])
n = np.array([17, 22, 19])
o = m@n
print(o)

[1852 2454 4305]


3. Lakukan Transpose, determinant, dan inverse terhadap matrix dibawah ini:

$$
\begin{bmatrix}
23 & 50 & 19 \\
7 & 12 & 109 \\
57 & 67 & 98
\end{bmatrix}
$$

In [4]:
m = np.array([[23, 50, 19],[ 7, 12, 109],[ 57, 67, 98]])
m_trans = m.T
print(m_trans)

[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]


In [7]:
inv_m = inv(m) 
print(inv_m)

[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]


In [8]:
det_m = det(m)
print(det(m))

131344.0000000002
