# Non Graded Challenge 6

_Non-Graded Assignment ini dibuat guna mengevaluasi pembelajaran pada Hacktiv8 Data Science Fulltime Program khususnya pada konsep Linear Algebra._

---

## Assignment Instructions

Apakah $\begin{bmatrix}1 \\3\end{bmatrix}$ adalah eigenvector dari $\begin{bmatrix}1 & -1\\6 &-4 \end{bmatrix}$? Jika iya, berapakah eigenvalue-nya?

## Assignment Submission

- Simpan assignment pada sesi ini dengan nama `h8dsft_Linear_Algebra3`.
- Push Assigment yang telah kalian buat ke akun Github kalian masing-masing.

## Assignment Objectives

Non-Graded Assignment ini dibuat guna mengevaluasi konsep Linear Algebra sebagai berikut:

- Memahami konsep eigenvalue dan eigenvector
- Dapat mencari eigenvalue dan eigenvector

### Name : Delfi Kusuma Wardhani
#### Batch : FTDS/002

In [5]:
from numpy import array
from numpy.linalg import eig
import numpy as np

In [3]:
A = array([[1],[3]])
B = array([[1,-1],[6,-4]])
values, vectors = eig(B)

print(values)
print(vectors)

[-1. -2.]
[[0.4472136  0.31622777]
 [0.89442719 0.9486833 ]]


eigen value dari dari array B adalah -1 dan -2

In [23]:
# mengalikan (dot product) array B dengan array A
c = B.dot(A)
c           # menghasilkan array c

array([[-2],
       [-6]])

In [21]:
# Mencoba membagi array c dengan eigen value = -1
c/values[0]

array([[2.],
       [6.]])

In [22]:
# Mencoba membagi array c dengan eigen value = -2
c/values[1]

array([[1.],
       [3.]])

Output di atas adalah array dari vector [[1],[3]], menandakan bahwa vector $\begin{bmatrix}1 \\3\end{bmatrix}$ adalah eigenvector dari $\begin{bmatrix}1 & -1\\6 &-4 \end{bmatrix}$